//go:build !ignore_autogenerated
// +build !ignore_autogenerated

package v1alpha1

import (
	zarfv1alpha1 "github.com/kylegalloway/forge/pkg/apis/zarf/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSBundle) DeepCopyInto(out *UDSBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSBundle.
func (in *UDSBundle) DeepCopy() *UDSBundle {
	if in == nil {
		return nil
	}
	out := new(UDSBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UDSBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSBundleList) DeepCopyInto(out *UDSBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UDSBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSBundleList.
func (in *UDSBundleList) DeepCopy() *UDSBundleList {
	if in == nil {
		return nil
	}
	out := new(UDSBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UDSBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSBundleSpec) DeepCopyInto(out *UDSBundleSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(zarfv1alpha1.PublishConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Deploy != nil {
		in, out := &in.Deploy, &out.Deploy
		*out = new(zarfv1alpha1.DeployConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RBACPolicy != nil {
		in, out := &in.RBACPolicy, &out.RBACPolicy
		*out = new(zarfv1alpha1.RBACPolicy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSBundleSpec.
func (in *UDSBundleSpec) DeepCopy() *UDSBundleSpec {
	if in == nil {
		return nil
	}
	out := new(UDSBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSBundleStatus) DeepCopyInto(out *UDSBundleStatus) {
	*out = *in
	if in.BuildStatus != nil {
		in, out := &in.BuildStatus, &out.BuildStatus
		*out = new(zarfv1alpha1.OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PublishStatus != nil {
		in, out := &in.PublishStatus, &out.PublishStatus
		*out = new(zarfv1alpha1.OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DeployStatus != nil {
		in, out := &in.DeployStatus, &out.DeployStatus
		*out = new(zarfv1alpha1.OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSBundleStatus.
func (in *UDSBundleStatus) DeepCopy() *UDSBundleStatus {
	if in == nil {
		return nil
	}
	out := new(UDSBundleStatus)
	in.DeepCopyInto(out)
	return out
}
