---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zarf-test-builder
  namespace: default
  annotations:
    forge.forge.dev/allowed-actions: "Build"
    forge.forge.dev/allowed-source-types: "Git"
    forge.forge.dev/allowed-source-repos: "*"

---
apiVersion: forge.dev/v1alpha1
kind: ZarfPackageJob
metadata:
  name: zarf-test-build
  namespace: default
spec:
  serviceAccountName: zarf-test-builder
  action: Build

  source:
    type: Git
    git:
      url: https://github.com/defenseunicorns/zarf
      ref: v0.32.0
      path: examples/dos-games
