---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: uds-test-builder
  namespace: default
  annotations:
    forge.forge.dev/allowed-actions: "Create"
    forge.forge.dev/allowed-source-types: "Git"
    forge.forge.dev/allowed-source-repos: "*"

---
apiVersion: forge.dev/v1alpha1
kind: UDSBundleJob
metadata:
  name: uds-test-create
  namespace: default
spec:
  serviceAccountName: uds-test-builder
  action: Create

  source:
    type: Git
    git:
      url: https://github.com/defenseunicorns/uds-core
      ref: v0.16.0
      path: bundles/k3d-standard
