apiVersion: v1
kind: Service
metadata:
  name: scriptrunner-controller-metrics
  namespace: scriptrunner-system
  labels:
    app: scriptrunner-controller
    component: metrics
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: scriptrunner-controller
  type: ClusterIP
