{{- if .Values.webhook.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterWide }}
kind: ClusterRole
{{- else }}
kind: Role
{{- end }}
metadata:
  name: {{ include "forge.fullname" . }}-webhook
  {{- if not .Values.rbac.clusterWide }}
  namespace: {{ include "forge.namespace" . }}
  {{- end }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["forge.dev"]
  resources: ["zarfpackagejobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.rbac.clusterWide }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  name: {{ include "forge.fullname" . }}-webhook
  {{- if not .Values.rbac.clusterWide }}
  namespace: {{ include "forge.namespace" . }}
  {{- end }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.rbac.clusterWide }}
  kind: ClusterRole
  {{- else }}
  kind: Role
  {{- end }}
  name: {{ include "forge.fullname" . }}-webhook
subjects:
- kind: ServiceAccount
  name: {{ include "forge.serviceAccountName" . }}-webhook
  namespace: {{ include "forge.namespace" . }}
{{- end }}
