{{- if and .Values.observability.otelCollector.enabled .Values.observability.deployStack .Values.observability.otelCollector.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "forge.fullname" . }}-otel-collector
  namespace: {{ include "forge.namespace" . }}
  labels:
    {{- include "forge.otel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "forge.otel.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: prometheus
    interval: {{ .Values.observability.otelCollector.serviceMonitor.interval }}
    path: /metrics
{{- end }}
