//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployConfig) DeepCopyInto(out *DeployConfig) {
	*out = *in
	if in.Kubeconfig != nil {
		in, out := &in.Kubeconfig, &out.Kubeconfig
		*out = new(KubeconfigReference)
		**out = **in
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployConfig.
func (in *DeployConfig) DeepCopy() *DeployConfig {
	if in == nil {
		return nil
	}
	out := new(DeployConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSource) DeepCopyInto(out *GitSource) {
	*out = *in
	if in.CredentialsSecretRef != nil { // pragma: allowlist secret
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.SecretReference) // pragma: allowlist secret
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSource.
func (in *GitSource) DeepCopy() *GitSource {
	if in == nil {
		return nil
	}
	out := new(GitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigReference) DeepCopyInto(out *KubeconfigReference) {
	*out = *in
	out.SecretRef = in.SecretRef // pragma: allowlist secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigReference.
func (in *KubeconfigReference) DeepCopy() *KubeconfigReference {
	if in == nil {
		return nil
	}
	out := new(KubeconfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSource) DeepCopyInto(out *LocalSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSource.
func (in *LocalSource) DeepCopy() *LocalSource {
	if in == nil {
		return nil
	}
	out := new(LocalSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIDestination) DeepCopyInto(out *OCIDestination) {
	*out = *in
	if in.CredentialsSecretRef != nil { // pragma: allowlist secret
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.SecretReference) // pragma: allowlist secret
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIDestination.
func (in *OCIDestination) DeepCopy() *OCIDestination {
	if in == nil {
		return nil
	}
	out := new(OCIDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCISource) DeepCopyInto(out *OCISource) {
	*out = *in
	if in.CredentialsSecretRef != nil { // pragma: allowlist secret
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.SecretReference) // pragma: allowlist secret
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCISource.
func (in *OCISource) DeepCopy() *OCISource {
	if in == nil {
		return nil
	}
	out := new(OCISource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperationStatus.
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil {
		return nil
	}
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageSource) DeepCopyInto(out *PackageSource) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSource)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Source)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCISource)
		(*in).DeepCopyInto(*out)
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageSource.
func (in *PackageSource) DeepCopy() *PackageSource {
	if in == nil {
		return nil
	}
	out := new(PackageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishConfig) DeepCopyInto(out *PublishConfig) {
	*out = *in
	in.Destination.DeepCopyInto(&out.Destination)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishConfig.
func (in *PublishConfig) DeepCopy() *PublishConfig {
	if in == nil {
		return nil
	}
	out := new(PublishConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublishDestination) DeepCopyInto(out *PublishDestination) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Destination)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCIDestination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublishDestination.
func (in *PublishDestination) DeepCopy() *PublishDestination {
	if in == nil {
		return nil
	}
	out := new(PublishDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Destination) DeepCopyInto(out *S3Destination) {
	*out = *in
	if in.CredentialsSecretRef != nil { // pragma: allowlist secret
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.SecretReference) // pragma: allowlist secret
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Destination.
func (in *S3Destination) DeepCopy() *S3Destination {
	if in == nil {
		return nil
	}
	out := new(S3Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Source) DeepCopyInto(out *S3Source) {
	*out = *in
	if in.CredentialsSecretRef != nil { // pragma: allowlist secret
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(v1.SecretReference) // pragma: allowlist secret
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Source.
func (in *S3Source) DeepCopy() *S3Source {
	if in == nil {
		return nil
	}
	out := new(S3Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSPackageJob) DeepCopyInto(out *UDSPackageJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSPackageJob.
func (in *UDSPackageJob) DeepCopy() *UDSPackageJob {
	if in == nil {
		return nil
	}
	out := new(UDSPackageJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UDSPackageJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSPackageJobList) DeepCopyInto(out *UDSPackageJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UDSPackageJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSPackageJobList.
func (in *UDSPackageJobList) DeepCopy() *UDSPackageJobList {
	if in == nil {
		return nil
	}
	out := new(UDSPackageJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UDSPackageJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSPackageJobSpec) DeepCopyInto(out *UDSPackageJobSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Publish != nil {
		in, out := &in.Publish, &out.Publish
		*out = new(PublishConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Deploy != nil {
		in, out := &in.Deploy, &out.Deploy
		*out = new(DeployConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSPackageJobSpec.
func (in *UDSPackageJobSpec) DeepCopy() *UDSPackageJobSpec {
	if in == nil {
		return nil
	}
	out := new(UDSPackageJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UDSPackageJobStatus) DeepCopyInto(out *UDSPackageJobStatus) {
	*out = *in
	if in.CreateStatus != nil {
		in, out := &in.CreateStatus, &out.CreateStatus
		*out = new(OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.PublishStatus != nil {
		in, out := &in.PublishStatus, &out.PublishStatus
		*out = new(OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.DeployStatus != nil {
		in, out := &in.DeployStatus, &out.DeployStatus
		*out = new(OperationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UDSPackageJobStatus.
func (in *UDSPackageJobStatus) DeepCopy() *UDSPackageJobStatus {
	if in == nil {
		return nil
	}
	out := new(UDSPackageJobStatus)
	in.DeepCopyInto(out)
	return out
}
