#!/bin/bash
set -e

echo "📈 Accessing Grafana and importing Forge dashboard..."
echo ""

# Get Grafana admin password
GRAFANA_PASSWORD=$(kubectl get secret -n monitoring kube-prometheus-stack-grafana -o jsonpath="{.data.admin-password}" | base64 -d)

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Grafana Access Information"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "First, port-forward Grafana:"
echo "  kubectl port-forward -n monitoring svc/kube-prometheus-stack-grafana 3000:80"
echo ""
echo "Then access Grafana:"
echo "🌐 URL: http://localhost:3000"
echo "👤 Username: admin"
echo "🔑 Password: ${GRAFANA_PASSWORD}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Import Forge Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open http://localhost:3000 in your browser"
echo "2. Login with the credentials above"
echo "3. Click 'Dashboards' → 'Import'"
echo "4. Click 'Upload JSON file'"
echo "5. Select: chart/forge/dashboards/forge-dashboard.json"
echo "6. Select 'Prometheus' as the data source"
echo "7. Click 'Import'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Prometheus Access"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To query Prometheus directly:"
echo "  kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090"
echo "  Then visit: http://localhost:9090"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📈 Example Prometheus Queries"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Custom Forge metrics (available after running test jobs):"
echo "  • forge_zarf_package_jobs_created_total"
echo "  • forge_zarf_package_jobs_active"
echo "  • forge_jobs_created_total{action=\"build\"}"
echo "  • forge_jobs_completed_total{action=\"deploy\"}"
echo "  • forge_builds_started_total"
echo "  • forge_builds_completed_total"
echo "  • forge_publishes_started_total"
echo "  • forge_publishes_completed_total"
echo "  • forge_deploys_started_total"
echo "  • forge_deploys_completed_total"
echo "  • forge_action_duration_seconds_bucket{action=\"build\"}"
echo "  • forge_reconcile_duration_seconds"
echo ""
echo "Go runtime metrics:"
echo "  • go_goroutines"
echo "  • go_memstats_alloc_bytes"
echo "  • go_gc_duration_seconds"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Verify Metrics Collection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check ServiceMonitor is discovered by Prometheus:"
echo "  1. Port-forward Prometheus: kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090"
echo "  2. Visit http://localhost:9090/targets"
echo "  3. Look for 'forge-system/forge-otel-collector' in the targets list"
echo ""
echo "Check OTEL Collector logs:"
echo "  kubectl logs -n forge-system -l app=otel-collector -f"
echo ""
echo "Check controller metrics endpoint:"
echo "  kubectl port-forward -n forge-system svc/forge-controller-metrics 8080:8080"
echo "  curl http://localhost:8080/metrics | grep forge_"
echo ""
echo "Test custom metrics are being recorded:"
echo "  1. Run a test ZarfPackageJob: ./scripts/local-dev/3-test-api.sh"
echo "  2. Query metrics: curl http://localhost:8080/metrics | grep forge_builds_started"
echo "  3. You should see metrics with labels like: forge_builds_started_total{namespace=\"forge-jobs\",package=\"hello-forge-test\"}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
