#!/bin/bash
set -e

echo "📈 Accessing Grafana and importing Forge dashboard..."
echo ""

# Get Grafana admin password
GRAFANA_PASSWORD=$(kubectl get secret -n monitoring kube-prometheus-stack-grafana -o jsonpath="{.data.admin-password}" | base64 -d)

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Grafana Access Information"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 URL: http://localhost:3000"
echo "👤 Username: admin"
echo "🔑 Password: ${GRAFANA_PASSWORD}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Import Forge Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open http://localhost:3000 in your browser"
echo "2. Login with the credentials above"
echo "3. Click 'Dashboards' → 'Import'"
echo "4. Click 'Upload JSON file'"
echo "5. Select: chart/forge/dashboards/forge-dashboard.json"
echo "6. Select 'Prometheus' as the data source"
echo "7. Click 'Import'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Prometheus Access"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To query Prometheus directly:"
echo "  kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090"
echo "  Then visit: http://localhost:9090"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📈 Example Prometheus Queries"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go runtime metrics (available now):"
echo "  • go_goroutines"
echo "  • go_memstats_alloc_bytes"
echo "  • go_gc_duration_seconds"
echo ""
echo "NOTE: Custom Forge metrics (forge_jobs_created_total, etc.) are"
echo "      planned but not yet implemented. The dashboard will show"
echo "      'No data' for these panels until metrics are added."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 Verify Metrics Collection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check ServiceMonitor is discovered by Prometheus:"
echo "  1. Port-forward Prometheus: kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090"
echo "  2. Visit http://localhost:9090/targets"
echo "  3. Look for 'forge-system/forge-otel-collector' in the targets list"
echo ""
echo "Check OTEL Collector logs:"
echo "  kubectl logs -n forge-system -l app.kubernetes.io/name=otel-collector -f"
echo ""
echo "Check controller metrics endpoint:"
echo "  kubectl port-forward -n forge-system svc/forge-controller-metrics 8080:8080"
echo "  curl http://localhost:8080/metrics"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
