apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scriptrunner-webhook-cert
  namespace: forge-system
  labels:
    app: scriptrunner-webhook
spec:
  secretName: scriptrunner-webhook-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
    - scriptrunner
  commonName: scriptrunner-webhook.forge-system.svc
  dnsNames:
  - scriptrunner-webhook
  - scriptrunner-webhook.forge-system
  - scriptrunner-webhook.forge-system.svc
  - scriptrunner-webhook.forge-system.svc.cluster.local
  issuerRef:
    name: scriptrunner-webhook-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: scriptrunner-webhook-issuer
  namespace: forge-system
  labels:
    app: scriptrunner-webhook
spec:
  selfSigned: {}
